services:
  - type: web
    name: unique-dress-api
    env: node
    region: oregon
    buildCommand: cd server && npm ci --only=production
    startCommand: cd server && node index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://notwins.netlify.app
      - key: GOOGLE_CLOUD_PROJECT_ID
        sync: false
      - key: GOOGLE_CLOUD_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_CLOUD_PRIVATE_KEY
        sync: false
      - key: GOOGLE_AI_API_KEY
        sync: false
    buildFilter:
      paths:
        - server/**/*