services:
  - type: web
    name: unique-dress-api
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: node server/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SCRAPER_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://notwins.netlify.app
      - key: GOOGLE_CLOUD_PROJECT_ID
        sync: false
      - key: GOOGLE_CLOUD_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_CLOUD_PRIVATE_KEY
        sync: false