// Color mappings with translations and variations
export const COLOR_MAPPINGS = {
  // English
  'black': 'Black',
  'white': 'White',
  'red': 'Red',
  'blue': 'Blue',
  'green': 'Green',
  'yellow': 'Yellow',
  'purple': 'Purple',
  'pink': 'Pink',
  'orange': 'Orange',
  'brown': 'Brown',
  'gray': 'Gray',
  'grey': 'Gray',
  'navy': 'Navy Blue',
  'beige': 'Beige',
  'cream': 'Cream',
  'ivory': 'Ivory',
  'gold': 'Gold',
  'silver': 'Silver',
  'bronze': 'Bronze',
  'burgundy': 'Burgundy',
  'maroon': 'Maroon',
  'teal': 'Teal',
  'olive': 'Olive',
  'khaki': 'Khaki',
  'pastel pink': 'Pastel Pink',
  'pastelrosa': 'Pastel Pink',
  'hellblau': 'Light Blue',
  'pastell': 'Pastel',
  'navy blue': 'Navy Blue',
  'light blue': 'Light Blue',
  'dark blue': 'Dark Blue',
  'light green': 'Light Green',
  'dark green': 'Dark Green',
  'light pink': 'Light Pink',
  'hot pink': 'Hot Pink',
  'light gray': 'Light Gray',
  'dark gray': 'Dark Gray',
  'coral': 'Coral',
  'turquoise': 'Turquoise',
  'lavender': 'Lavender',
  'mint': 'Mint',
  'salmon': 'Salmon',
  'plum': 'Plum',
  'indigo': 'Indigo',
  'violet': 'Violet',
  'magenta': 'Magenta',

  // Spanish
  'negro': 'Black',
  'blanco': 'White',
  'rojo': 'Red',
  'azul': 'Blue',
  'verde': 'Green',
  'amarillo': 'Yellow',
  'morado': 'Purple',
  'rosa': 'Pink',
  'naranja': 'Orange',
  'marrón': 'Brown',
  'marron': 'Brown',
  'gris': 'Gray',
  'dorado': 'Gold',
  'plateado': 'Silver',
  'beige': 'Beige',
  'crema': 'Cream',
  'marfil': 'Ivory',
  'azul marino': 'Navy Blue',
  'azul claro': 'Light Blue',
  'verde claro': 'Light Green',
  'verde oscuro': 'Dark Green',
  'rosa claro': 'Light Pink',
  'rosa fuerte': 'Hot Pink',
  'gris claro': 'Light Gray',
  'gris oscuro': 'Dark Gray',
  'coral': 'Coral',
  'turquesa': 'Turquoise',
  'lavanda': 'Lavender',
  'menta': 'Mint',
  'salmón': 'Salmon',
  'ciruela': 'Plum',
  'índigo': 'Indigo',
  'violeta': 'Violet',
  'magenta': 'Magenta',

  // German
  'schwarz': 'Black',
  'weiß': 'White',
  'weiss': 'White',
  'rot': 'Red',
  'blau': 'Blue',
  'grün': 'Green',
  'gelb': 'Yellow',
  'lila': 'Purple',
  'rosa': 'Pink',
  'orange': 'Orange',
  'braun': 'Brown',
  'grau': 'Gray',
  'golden': 'Gold',
  'silber': 'Silver',
  'beige': 'Beige',
  'creme': 'Cream',
  'elfenbein': 'Ivory',
  'marineblau': 'Navy Blue',
  'hellblau': 'Light Blue',
  'dunkelblau': 'Dark Blue',
  'hellgrün': 'Light Green',
  'dunkelgrün': 'Dark Green',
  'hellrosa': 'Light Pink',
  'hellgrau': 'Light Gray',
  'dunkelgrau': 'Dark Gray',
  'koralle': 'Coral',
  'türkis': 'Turquoise',
  'lavendel': 'Lavender',
  'minze': 'Mint',
  'lachs': 'Salmon',
  'pflaume': 'Plum',
  'indigo': 'Indigo',
  'violett': 'Violet',
  'magenta': 'Magenta'
};